[app]
page_title = "Recruitment Need Analysis"
page_icon = "🏠"
layout = "wide"
theme = "dark"  # Options could be 'light', 'dark', 'auto'

[api]
groq_key = "YOUR_GROQ_KEY_HERE"

[pages]

# Home Page Configurations
home_page_title = "Welcome to the Future of Recruitment"
home_page_subtitle = "Effortlessly pinpoint the right skills for your next hire"
home_page_intro = """
Recruiting the right talent is no longer about guesswork or relying solely on intuition—it’s about precision, data, and understanding. 
Our Recruitment Need Analysis tool empowers you to effortlessly pinpoint the skills, experience, and attributes your next hire should possess. 
With a clean, smart, and secure interface, you'll streamline your hiring process, save time, and find the right fit for your organization.
"""

# Mission Page Configurations
mission_title = "Our Mission"
mission_subtitle = "Transforming recruitment, one step at a time."
mission_content = """
Our mission is simple yet powerful: to transform recruitment from a daunting process into an empowering experience. 
We believe that hiring the right person for the right role is the foundation of every successful company. By delivering a recruitment analysis 
tool that is insightful, easy to use, and profoundly secure, we empower recruiters and managers to make informed decisions with precision and clarity.
"""

# The Magic Behind the Scenes Page Configurations
behind_scenes_title = "The Magic Behind the Scenes"
behind_scenes_subtitle = "How we blend technology with recruitment expertise."
behind_scenes_content = """
What makes our Recruitment Need Analysis tool extraordinary? The answer lies in our innovative blend of cutting-edge technology and deep recruitment expertise. 
Behind the intuitive interface, we harness the power of advanced NLP models, data analytics, and machine learning to simplify the complex dynamics of hiring.
We analyze market trends, skill requirements, and role-specific nuances to provide you with hyper-relevant suggestions tailored to your specific needs.
"""

# Benefits Page Configurations
benefits_title = "Benefits for Your Team"
benefits_subtitle = "What you'll gain with our analysis tool"
benefits_content = """
Our Recruitment Need Analysis tool is built with you in mind. By identifying exactly what you need in a candidate, 
you reduce the time spent on finding the right fit, minimize hiring mistakes, and ultimately build a stronger team with a streamlined, data-driven approach.
"""

# Recruitment Process Page Configurations
recruitment_process_title = "Streamline Your Recruitment Process"
recruitment_process_subtitle = "See how the process can become smarter and faster"
recruitment_process_content = """
Our tool helps you from the beginning to the end of the recruitment journey—understanding the need, analyzing the candidate profile, 
and selecting the right match. Each step is designed to be seamless and integrated with your goals.
"""

# Job Advertisement Page Configurations
job_ad_title = "Your Customized Job Advertisement"
job_ad_subtitle = "Precision-crafted job ads for targeted outreach"
job_ad_content = """
With the provided data, our tool generates highly tailored job advertisements that attract the best candidates. 
It uses insights from the company information, role requirements, and more to ensure you present the opportunity in the most appealing manner.
"""

[security]
use_https = true
data_protection_level = "high"
encryption_method = "AES256"  # Choose from 'AES128', 'AES256', etc.
user_authentication = "OAuth2"  # Authentication method used for the app

[features]
enable_dynamic_skill_suggestions = true
use_sentiment_analysis = true
enable_realtime_collaboration = false  # Allow multiple recruiters to work on the same page in real-time
